title: "Shatakshi Bhatnagar's Portfolio"
description: "Portfolio showcasing my projects in data science, marketing analytics, and AI."
baseurl: "" # Use this if you are hosting your portfolio in a subpath (e.g., `/devportfolio`)
url: "https://yourusername.github.io" # Update with your own GitHub pages URL or domain

# Theme Configuration
theme: jekyll-theme-devfolio

# Social Links
social_links:
  - { name: "LinkedIn", url: "https://www.linkedin.com/in/shatakshibhatnagar/", icon: "fab fa-linkedin" }
  - { name: "GitHub", url: "https://github.com/shatakshi99", icon: "fab fa-github" }
  - { name: "Email", url: "mailto:sb99@illinois.edu", icon: "fas fa-envelope" }

# Sections (Customize your sections below)
sections:
  - title: "About Me"
    content: "I am a data scientist and marketing analyst focused on deriving actionable insights from data."

  - title: "Skills"
    content:
      - "Programming: Python, R, SQL, SPSS"
      - "Data Analysis: Excel, Tableau, Power BI"
      - "Web Analytics: Google Analytics, Hotjar, Semrush"

  - title: "Projects"
    content:
      - { name: "AI Candidate Sourcing Tool", description: "Automated sourcing with LLMs", link: "#" }
      - { name: "Price Forecasting Model", description: "Random Forest model for Tata Metaliks", link: "#" }

# Additional Settings
permalink: pretty
paginate: 5

# Customization Options
avatar: "assets/images/profile.jpg" # Ensure the image exists in the assets folder

